[REL] Tagging release

diff --git a/doc/devtools/tim/tim b/doc/devtools/tim/tim
--- a/doc/devtools/tim/tim
+++ b/doc/devtools/tim/tim
@@ -12,15 +12,16 @@ usage()
 {
 cat << EOF
 TIM - Tiki Instance Manager
-usage: $0 -c <command>[:subcommand] -u <user> -t <svn tag> -i <instance id>
+usage: $0 -c <command> -u <user> -t <svn tag> -i <instance id>
 
 OPTIONS:
    -h      Show this message
-   -c      Command (one of: create, destroy, snapshot, debug, info[:versions|diskspace], update, reset)
+   -c      Command (one of: create, destroy, snapshot, debug, info, upgrade, reset)
    -i      id of instance
    -u      username on Tiki.org 
    -U      userid on Tiki.org 
    -t      SVN Tag (Tiki version)
+   -s      subcommand (with command info) (one of: versions)
    -p      admin password (simple passwords only)
    -P      Subdirectory path
 EOF
@@ -36,10 +37,7 @@ do
 		c)
 			# SSH always passes -c, so we catch it
 			# maybe we can use it later
-			COMMAND=$(echo "$OPTARG" | tr A-Z a-z | sed -e 's/[^a-z:]//g' | sed -e 's/:.*//')
-			# TODO: Have a regex that does this correctly without the need for the unset hack
-			SUBCOMMAND=$(echo "$OPTARG" | tr A-Z a-z | sed -e 's/[^a-z:]//g' | sed -e 's/[^:]*:\(.*\)/\1/')
-			if [ "$SUBCOMMAND" = "$COMMAND" ]; then unset SUBCOMMAND; fi
+			COMMAND=$(echo "$OPTARG" | tr A-Z a-z | sed -e 's/[^a-z]//g')
 			;;
 		i)
 			ID=$(echo "$OPTARG" | sed -e 's/[^0-9]//g')
@@ -56,6 +54,9 @@ do
 			;;
 		p)
 			APASSWORD=$(echo "$OPTARG" | sed -e 's/[^a-zA-Z0-9.]//g')
+			;;
+		s)
+			SUBCOMMAND=$(echo "$OPTARG" | tr A-Z a-z | sed -e 's/[^a-z]//g')
 			;;
 		P)
 			TPATH="$OPTARG"
@@ -87,23 +88,16 @@ debug()
 
 destroy()
 {
-	startlog
-	log "Dropping database"
 	mysql -e "DROP DATABASE $DB;" && echo "DATABASE $DB suppressed" || echo "ERROR: database $DB not suppressed"
-
-	log "Removing webroot"
 	rm -r $INSTANCE_DIR && echo "FILES in $INSTANCE_DIR suppressed" || echo "ERROR: FILES in $INSTANCE_DIR not suppressed"
-
-	# No use logging after this point as we log into the webroot
-	if [[ -f $INSTANCE_LOCK ]] 
+	if [[ -f $LOCKSDIR/lock_${TUSERID}_${ID} ]] 
 	then
-		rm $INSTANCE_LOCK && echo "LOCK file removed" || echo "ERROR: LOCK file could not be removed"
+		rm $LOCKSDIR/lock_${TUSERID}_${ID} && echo "LOCK file removed" || echo "ERROR: LOCK file could not be removed"
 	fi
 }
 
 reset()
 {
-	startlog
 	# Use detected database name unless there is none, then use expected
 	# If detected and expected don't match, display warning
 	# If none, display error and abort
@@ -132,19 +126,10 @@ reset()
 	mysql -e "UPDATE users_users SET password='admin', hash= md5('${APASSWORD}') WHERE login='admin';" $DB_DETECTED && echo "SUCCESS: Admin password reset to ${APASSWORD} in database ${DB_DETECTED}" || echo "ERROR: admin password not reset in database ${DB_DETECTED}"
 }
 
-update()
+upgrade()
 {
-	startlog
-	echo "UPDATE" > $INSTANCE_LOCK
 	cd $INSTANCE_DIR
-	log "SVN upping"
 	svn up
-	log "Running setup.sh"
-	sh setup.sh -u $TIM_USER -g $TIM_GROUP -n fix
-	log "Running php console.php d:u (database upgrade)"
-	php console.php d:u
-	mk_info
-	rm $INSTANCE_LOCK
 }
 
 info()
@@ -185,12 +170,11 @@ info()
 			elif [[ $(ls -d -1 *-${TUSERID}-${ID} 2>/dev/null | wc -l ) == 1 ]]
 			then 
 				SUBDOMAIN=$(ls -d -1 *-${TUSERID}-${ID})
-				if [[ -e $INSTANCE_LOCK ]]
+				if [[ -e $LOCKSDIR/lock_${TUSERID}_${ID} ]]
 				then
-					echo "STATUS: $INSTANCE_LOCK_REASON"
+					echo "STATUS: BUILDING"
 				else
 					echo "STATUS: ACTIVE"
-					grep Version $WEBROOT/$SUBDOMAIN/info.txt | sed -e 's/Version/VERSION/'
 				fi
 				if [[ ! -z $TUSER ]] && [[ "${SUBDOMAIN}" != "$TUSER-$TUSERID-$ID" ]]
 				then
@@ -202,9 +186,9 @@ info()
 				SUBDOMAIN=$(ls -d -1 *-${TUSERID}-${ID})
 				if [[ ! -z $TUSER ]] && [[ -d "$TUSER-$TUSERID-$ID" ]]
 				then
-					if [[ -e $INSTANCE_LOCK ]]
+					if [[ -e $LOCKSDIR/lock_${TUSERID}_${ID} ]]
 					then
-						BEINGBUILT=$(/bin/cat "${INSTANCE_LOCK}")
+						BEINGBUILT=$(/bin/cat "${LOCKSDIR}/lock_${TUSERID}_${ID}")
 						if [[ "${BEINGBUILT}" == "${TUSER}" ]]
 						then
 							echo "STATUS: BUILDING"
@@ -231,23 +215,24 @@ info()
 case ${COMMAND} in
 	create)
 		# TODO: Check INSTANCE_DIR not exists
+		# TODO: Find next ID and use that instead of -i
+		# TODO: Make use of userId (option -U)
 		if [[ -z $TUSERID ]] || [[ -z $SVNTAG ]]
 		then
 			echo "FAIL: Missing parameters"
 			usage
 			exit 1
 		fi
-
+		if [[ -z $TUSER ]]
+		then
+			TUSER="user"
+		fi
 		echo "START: ${COMMAND}"
 		echo "SITE: ${SUBDOMAIN}.show.tikiwiki.org "
 		echo "LOG: http://${SUBDOMAIN}.show.tikiwiki.org/install_log.txt (available after a delay)"
-		if [[ -d $INSTANCE_DIR ]];
-		then
-			echo "FAIL: Instance exists"
-			exit 1
-		fi
+		mkdir $INSTANCE_DIR || echo "FAIL: $INSTANCE_DIR not created"
 		# This is simply too long for synchronous feedback
-		$PREFIX/tim-create -t "$SVNTAG" -u "$TUSER" -U "$TUSERID" -i "$ID" &
+		nohup $PREFIX/tim-create -t "$SVNTAG" -u "$TUSER" -U "$TUSERID" -i "$ID" 1>$INSTANCE_DIR/install_log.txt 2>&1 &
 		exit 0
 		;;
 	destroy)
@@ -307,7 +292,7 @@ case ${COMMAND} in
 		# TODO: Show links
 		exit 0
 		;;
-	update)
+	upgrade)
 		if [[ -z $TUSERID ]] || [[ -z $ID ]]
 		then
 			usage
