[REL] Tagging release

diff --git a/doc/devtools/tim/tim-create b/doc/devtools/tim/tim-create
--- a/doc/devtools/tim/tim-create
+++ b/doc/devtools/tim/tim-create
@@ -158,21 +158,14 @@ EOF
 
 	chown $TIM_USER.$TIM_GROUP $INSTANCE_DIR/db/local.php
 
-	if [[ -f $INSTANCE_DIR/console.php ]]
+	if [[ -f $INSTANCE_DIR/installer/shell.php ]]
 	then
-		log "Running 'php console.php'"
+		log "Running 'php installer/shell.php'"
 		cd $INSTANCE_DIR
-		php console.php database:install --force
+		/usr/bin/php installer/shell.php install
 	else
-		if [[ -f $INSTANCE_DIR/installer/shell.php ]]
-		then
-			log "Running 'php installer/shell.php'"
-			cd $INSTANCE_DIR
-			/usr/bin/php installer/shell.php install
-		else
-			log "Old Tiki - populating database via tiki.sql"
-			mysql $DB < $INSTANCE_DIR/db/tiki.sql
-		fi
+		log "Old Tiki - populating database via tiki.sql"
+		mysql $DB < $INSTANCE_DIR/db/tiki.sql
 	fi
 
 	#########################################
@@ -199,8 +192,13 @@ EOT
 	echo "Creating file http://${SUBDOMAIN}.show.tikiwiki.org/info.txt with extra info for developers"
 	INFOFILE=$INSTANCE_DIR/info.txt
 	echo "$infotext" > ${INFOFILE}
-	# Cannot inject data useful to developers as remarksbox on top of homepage because page is not created et until first login
+	# Inject data useful to developers as remarksbox on top of homepage
+	echo "Inserting extra info for developers in a box at the beginning of homepage"
+	mysql $DB <<EOQ
+UPDATE tiki_pages SET data=CONCAT('{REMARKSBOX(type="information" title="Show community server" close="y")}${infotext}{REMARKSBOX}\n',data) WHERE page_id=1;
+EOQ
 
+	/bin/rm $LOCKSDIR/lock_${TUSERID}_${ID} || (echo "FAIL: Failed to suppress lock file $LOCKSDIR/lock_${TUSERID}_${ID}"; exit 1)
 }
 
 echo "CREATION START - watch ${SUBDOMAIN}.show.tikiwiki.org "
