[REL] Tagging release

diff --git a/doc/devtools/tim/tim-create b/doc/devtools/tim/tim-create
--- a/doc/devtools/tim/tim-create
+++ b/doc/devtools/tim/tim-create
@@ -8,24 +8,6 @@ setup()
 		. $MY_PATH/tim-common
 }
 
-#--- onexit() -----------------------------------------------------
-#  @param $1 integer  (optional) Exit status.  If not set, use `$?'
-function onexit() {
-    local exit_status=${1:-$?}
-    if [ $exit_status != 0 ];
-    then
-	log "FAILED INSTALL"
-	echo "FAILED INSTALL" > ${INSTANCE_LOCK}
-    else
-	log "FINISHED SUCCESSFULLY"
-	rm ${INSTANCE_LOCK}
-    fi
-    echo Exiting $0 with exit status: $exit_status
-    exit $exit_status
-}
-
-trap onexit 1 2 3 15 ERR
-
 usage()
 {
 cat << EOF
@@ -89,59 +71,32 @@ debug()
 
 create()
 {
-	# tim-create runs as a separate process and doesn't know $COMMAND
-	# we set it manually here to be shown in logs
-	COMMAND="create"
-
-	if [[ -e $INSTANCE_LOCK ]] ; then echo "FAIL: Lock file already exists. Reason: $INSTANCE_LOCK_REASON."; exit 1; fi
+	if [[ -e $LOCKSDIR/lock_${TUSERID}_${ID} ]] ; then echo "FAIL: Lock file already exists. Another install is being performed"; exit 1; fi
 	#TODO: remove stale locks
-
-	if ! mkdir $INSTANCE_DIR;
-	then
-		echo "FAIL: $INSTANCE_DIR not created"
-		echo "FAILED: mkdir - contact admin" > ${INSTANCE_LOCK}
-		exit 1
-	fi
-
-	echo "CREATE" > "${INSTANCE_LOCK}" || (echo "FAIL: Failed to create lock file ${INSTANCE_LOCK}"; exit 1)
-
-	# Can only be called here because $INSTANCE_DIR needs to exist for $INSTANCE_LOG
-	startlog
-
-	log "Starting instance creation"
+	echo "${TUSER}" > "${LOCKSDIR}/lock_${TUSERID}_${ID}" || (echo "FAIL: Failed to create lock file ${LOCKSDIR}/lock_${TUSERID}_${ID}"; exit 1)
 
 	# Trunk cache gets updated via cron every now and then
 	# we lock it, so we don't install from a broken tarball
 	while [[ -e $SVN_CACHE/$SVNTAG.lock ]];
 	do
-		log "Waiting for tarball lock"
 		sleep 5
 	done
 
-	log "Unpacking tarball"
 	tar -C $INSTANCE_DIR -xzf $SVN_CACHE/$SVNTAG.tar.gz
 
-	if echo $BRANCHES | grep ${SVNTAG} > /dev/null;
+	if [[ 'trunk' == "${SVNTAG}" ]]
 	then
-		log "SVN upping because this is $SVNTAG"
 		cd $INSTANCE_DIR
 		svn up
 	fi
 
-	log "Chown-ing everything to TIM user and group"
 	chown -R $TIM_USER.$TIM_GROUP $INSTANCE_DIR
-
-	log "Running setup.sh"
 	cd $INSTANCE_DIR
 	sh setup.sh -u $TIM_USER -g $TIM_GROUP -n fix
 
-	log "Creating database"
 	mysql -e "CREATE DATABASE $DB;"
-
-	log "Setting GRANTs on database"
 	mysql -e "GRANT ALL ON $DB.* TO tiki@localhost IDENTIFIED BY 'password';"
 
-	log "Creating local.php"
 	cat > $INSTANCE_DIR/db/local.php <<EOF
 <?php
 \$db_tiki='mysql';
@@ -160,17 +115,15 @@ EOF
 
 	if [[ -f $INSTANCE_DIR/installer/shell.php ]]
 	then
-		log "Running 'php installer/shell.php'"
 		cd $INSTANCE_DIR
 		/usr/bin/php installer/shell.php install
 	else
-		log "Old Tiki - populating database via tiki.sql"
 		mysql $DB < $INSTANCE_DIR/db/tiki.sql
 	fi
 
 	#########################################
 	# Start custom changes for show instances
-	log "Starting extra steps special to show instances. Anything done below is not part of a standard Tiki installation."
+	echo "Starting extra steps special to show instances. Anything done below is not part of a standard Tiki installation."
 
 	# Collect data useful to developers in infotext
 	if [[ "${TUSER}" != "user" ]]; then FRIENDLYUSERNAME="${TUSER}"; fi
